{
  ExceptionMessage: Cannot access error of successful result
}